from pydantic import BaseModel, Field
from typing import List, Dict, Optional, Any

class VisualEvidence(BaseModel):
    artifact_type: str  # e.g., "actual_ss", "annotated_ss", "pixel_diff", "diagram"
    file_path: str
    vlm_description: Optional[str] = None  # Text generated by VLM for diagrams

class ParsedItem(BaseModel):
    item_id: str  # Extracted ID (e.g., "REQ-001", "TC_102") or auto-generated hash
    parent_doc_id: str  # Extracted Doc ID (e.g., "D001331681")
    section_path: str  # e.g., "D001331681 / Functional_Reqs / Section 3.1"
    item_type: str  # "REQUIREMENT", "TEST_CASE", "DESIGN_SPEC"
    title: Optional[str] = None
    text_content: str
    metadata: Dict[str, Any] = Field(default_factory=dict)  # Excel columns, custom attributes
    visual_evidence: List[VisualEvidence] = Field(default_factory=list)
    missing_artifacts: List[str] = Field(default_factory=list)  # Flags for missing expected images, etc.

class IngestionOutput(BaseModel):
    document_id: str
    source_filename: str
    source_type: str  # "DOCX", "PDF", "EXCEL", "TEST_FOLDER"
    doc_class: str = "UNKNOWN"  # Logical class used by the linker: PRS, PTD, TEST, RMM
    total_items_extracted: int
    items: List[ParsedItem]